version = 1

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Watemlifts/markdown-it"

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs"
  ]

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true